version: 2.1
orbs:
  node: circleci/node@2.1.0
jobs:
  all:
    docker:
      - image: cypress/base:12
    steps:
      - checkout
      - node/install-packages
      - run: npm run affected:lint -- --all
      - run: npm run affected:test -- --all
      - run: npm run affected:e2e -- --all
  affected:
    docker:
      - image: cypress/base:12
    steps:
      - checkout
      - node/install-packages
      - run: npm run affected:lint -- --base origin/master --head HEAD
      - run: npm run affected:test -- --base origin/master --head HEAD
      - run: npm run affected:e2e -- --base origin/master --head HEAD
workflows:
  version: 2
  default:
    jobs:
      - all:
          filters:
            branches:
              only: 
                - master
      - affected:
          filters:
            branches:
              ignore: 
                - master
